# Imagen de Python
FROM python:3.8

# Setea el directorio de trabajo
WORKDIR /app

# Copia en /app el archivo
COPY hola_mundo.py .

# Comando que ejecuta al hacer docker run
CMD ["python", "-u", "hola_mundo.py"]