/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterFazGraFica;

import Clases.*;
import Interfaces.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lithium582
 */
public class frmBuscarVentas extends javax.swing.JFrame {

    private final Farmacia farmaArticulos;
    /**
     * Creates new form NuevoArticulo
     */
    
    public frmBuscarVentas() {
        initComponents();
        
        farmaArticulos = null;
        this.setSize(690,420);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }
    
    public frmBuscarVentas(Farmacia pFarma) {
        initComponents();
        
        farmaArticulos = pFarma;
        
        this.dgVentas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.dgVentas.setRowSelectionAllowed(true);
        this.dgVentas.setRowSelectionAllowed(true);
        
        this.setSize(690,420);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarXID = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtIDArticulo = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtIDArticuloPromedio = new javax.swing.JTextField();
        btnBuscarPromedio = new javax.swing.JButton();
        btnCerrarForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgVentas = new javax.swing.JTable();
        btnLimpiarGrilla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Ventas");

        btnBuscarXID.setText("Buscar");
        btnBuscarXID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarXIDActionPerformed(evt);
            }
        });

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("ID de artículo");

        txtIDArticulo.setToolTipText("ID de Artículo");
        txtIDArticulo.setName(""); // NOI18N

        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Promedio de ventas mensual");

        txtIDArticuloPromedio.setToolTipText("Precio de Artículo");
        txtIDArticuloPromedio.setName(""); // NOI18N

        btnBuscarPromedio.setText("Buscar");
        btnBuscarPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPromedioActionPerformed(evt);
            }
        });

        btnCerrarForm.setText("Cerrar");
        btnCerrarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFormActionPerformed(evt);
            }
        });

        dgVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID","Fecha","ID Articulo","Valor Final","Cantidad"
            }
        ));
        jScrollPane1.setViewportView(dgVentas);

        btnLimpiarGrilla.setText("Limpiar");
        btnLimpiarGrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarGrillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnCerrarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPrecio)
                                .addGap(24, 24, 24)
                                .addComponent(txtIDArticuloPromedio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblID)
                                .addGap(109, 109, 109)
                                .addComponent(txtIDArticulo)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarXID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtIDArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarXID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtIDArticuloPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblPrecio.getAccessibleContext().setAccessibleName("Preci");

        getAccessibleContext().setAccessibleName("Búsquedas de Artículos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarXIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarXIDActionPerformed
        try{
            Integer idProd = Integer.parseInt(this.txtIDArticulo.getText());
            ILista<IMovimiento> listaVentas = this.farmaArticulos.buscarVentasXProducto(idProd);
            if (listaVentas == null){
                JOptionPane.showMessageDialog(null, "No hay ventas ingresadas", "Atención", JOptionPane.WARNING_MESSAGE);
            }else{
                this.dgVentas.setRowSelectionAllowed(true);
                this.dgVentas.setRowSelectionAllowed(true);
                DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();

                if (listaVentas != null){
                    INodoLista<IMovimiento> nodoActual = listaVentas.getPrimero();

                while (nodoActual != null){
                    IMovimiento ventaActual = nodoActual.getObjeto();
                        if (ventaActual != null){
                            String[] prodInfo = new String[12];
                            prodInfo[0] = (ventaActual.getID()).toString();
                            prodInfo[1] = ventaActual.GetFecha().toString();
                            prodInfo[2] = (ventaActual.GetIdArticulo()).toString();
                            prodInfo[3] = Double.toString(ventaActual.GetValorFinal());
                            prodInfo[4] = Integer.toString(ventaActual.GetCantidad());

                            elementTable.addRow(prodInfo);
                        }
                    nodoActual = nodoActual.getSiguiente();
                }
            }
        }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Ha habido un error al leer los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarXIDActionPerformed

    private void btnBuscarPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPromedioActionPerformed
        try{
            Integer idProd = Integer.parseInt(this.txtIDArticuloPromedio.getText());
            Double prom = this.farmaArticulos.promedioVentasXArticulo(idProd);
            LimpiarTabla();
            
            JOptionPane.showMessageDialog(null, "El promedio mensual de ventas para el artículo: " + Integer.toString(idProd) + "es de: " + Double.toString(prom), "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Ha habido un error al leer los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarPromedioActionPerformed

    private void LimpiarTabla(){
        DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
        elementTable.setRowCount(0);
    }
    
    private void btnCerrarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFormActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarFormActionPerformed

    private void btnLimpiarGrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarGrillaActionPerformed
        DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
        elementTable.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarGrillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuscarVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPromedio;
    private javax.swing.JButton btnBuscarXID;
    private javax.swing.JButton btnCerrarForm;
    private javax.swing.JButton btnLimpiarGrilla;
    private javax.swing.JTable dgVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtIDArticulo;
    private javax.swing.JTextField txtIDArticuloPromedio;
    // End of variables declaration//GEN-END:variables
}
