/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterFazGraFica;

import Clases.*;
import Interfaces.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lithium582
 */
public class frmListarVentasXFecha extends javax.swing.JFrame {

    private final Farmacia farmaArticulos;
    /**
     * Creates new form NuevoArticulo
     */
    
    public frmListarVentasXFecha() {
        initComponents();
        
        farmaArticulos = null;
        this.setSize(690,405);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }
    
    public frmListarVentasXFecha(Farmacia pFarma) {
        initComponents();
        
        farmaArticulos = pFarma;
        
        this.dgVentas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.dgVentas.setRowSelectionAllowed(true);
        this.dgVentas.setRowSelectionAllowed(true);
        
        this.setSize(690,405);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarXID = new javax.swing.JButton();
        lblFechaDesde = new javax.swing.JLabel();
        txtFechaDesde = new javax.swing.JTextField();
        lblFechaHasta = new javax.swing.JLabel();
        txtFechaHasta = new javax.swing.JTextField();
        btnCerrarForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgVentas = new javax.swing.JTable();
        btnLimpiarGrilla = new javax.swing.JButton();
        lblFormato1 = new javax.swing.JLabel();
        lblFormato2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas por Fecha");

        btnBuscarXID.setText("Buscar");
        btnBuscarXID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarXIDActionPerformed(evt);
            }
        });

        lblFechaDesde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaDesde.setText("Fecha Desde");

        txtFechaDesde.setToolTipText("ID de Artículo");
        txtFechaDesde.setName(""); // NOI18N

        lblFechaHasta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaHasta.setText("Fecha Hasta");

        txtFechaHasta.setToolTipText("Nombre de Artículo");
        txtFechaHasta.setName(""); // NOI18N

        btnCerrarForm.setText("Cerrar");
        btnCerrarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFormActionPerformed(evt);
            }
        });

        dgVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID","Fecha","ID Articulo","Valor Final","Cantidad"
            }
        ));
        jScrollPane1.setViewportView(dgVentas);

        btnLimpiarGrilla.setText("Limpiar");
        btnLimpiarGrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarGrillaActionPerformed(evt);
            }
        });

        lblFormato1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormato1.setText("Formato: dd-mm-yyyy");

        lblFormato2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormato2.setText("Formato: dd-mm-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(480, Short.MAX_VALUE)
                        .addComponent(btnLimpiarGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblFechaDesde)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFormato1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtFechaDesde))
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFormato2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtFechaHasta))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscarXID, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDesde)
                    .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaHasta)
                    .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormato1)
                    .addComponent(lblFormato2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarXID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Búsquedas de Artículos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarXIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarXIDActionPerformed
        try{
            String fecha1 = this.txtFechaDesde.getText();
            String fecha2 = this.txtFechaHasta.getText();

            SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");

            try{
                Date dateFecha1 = dt.parse(fecha1);
                Date dateFecha2 = dt.parse(fecha2);
                dateFecha2.setTime(dateFecha2.getTime() + 86400000L);

                ILista<IMovimiento> listaVentas = farmaArticulos.ListadoVenta(dateFecha1.getTime(), dateFecha2.getTime());

                if (listaVentas == null){
                    JOptionPane.showMessageDialog(null, "No hay ventas en ese rango", "Atención", JOptionPane.WARNING_MESSAGE);
                } else{
                    this.dgVentas.setRowSelectionAllowed(true);
                    this.dgVentas.setRowSelectionAllowed(true);
                    DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
                    
                    LimpiarTabla();
                    
                    if (listaVentas != null){
                    INodoLista<IMovimiento> nodoActual = listaVentas.getPrimero();

                    while (nodoActual != null){
                        IMovimiento ventaActual = nodoActual.getObjeto();
                            if (ventaActual != null){
                                String[] prodInfo = new String[12];
                                prodInfo[0] = (ventaActual.getID()).toString();
                                prodInfo[1] = ventaActual.GetFecha().toString();
                                prodInfo[2] = (ventaActual.GetIdArticulo()).toString();
                                prodInfo[3] = Double.toString(ventaActual.GetValorFinal());
                                prodInfo[4] = Integer.toString(ventaActual.GetCantidad());

                                elementTable.addRow(prodInfo);
                            }
                        nodoActual = nodoActual.getSiguiente();
                    }
                }
                    
                }
            }catch(Exception ex){
                System.out.println("Las fechas son inválidas. Verifique el formato requerido!");
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Ha habido un error al leer los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarXIDActionPerformed

    private void LimpiarTabla(){
        DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
        elementTable.setRowCount(0);
    }
    
    private void btnCerrarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFormActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarFormActionPerformed

    private void btnLimpiarGrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarGrillaActionPerformed
        DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
        elementTable.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarGrillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarVentasXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarVentasXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarVentasXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarVentasXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarVentasXFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarXID;
    private javax.swing.JButton btnCerrarForm;
    private javax.swing.JButton btnLimpiarGrilla;
    private javax.swing.JTable dgVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaDesde;
    private javax.swing.JLabel lblFechaHasta;
    private javax.swing.JLabel lblFormato1;
    private javax.swing.JLabel lblFormato2;
    private javax.swing.JTextField txtFechaDesde;
    private javax.swing.JTextField txtFechaHasta;
    // End of variables declaration//GEN-END:variables
}
