/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterFazGraFica;

import Clases.*;
import Interfaces.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lithium582
 */
public class frmMovimientosXArea extends javax.swing.JFrame {

    private final Farmacia farmaArticulos;
    /**
     * Creates new form NuevoArticulo
     */
    
    public frmMovimientosXArea() {
        initComponents();
        
        farmaArticulos = null;
        this.setSize(690,405);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }
    
    public frmMovimientosXArea(Farmacia pFarma) {
        initComponents();
        
        farmaArticulos = pFarma;
        
        this.dgVentas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.dgVentas.setRowSelectionAllowed(true);
        this.dgVentas.setRowSelectionAllowed(true);
        
        this.setSize(690,405);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarXID = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnCerrarForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgVentas = new javax.swing.JTable();
        btnLimpiarGrilla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgCompras = new javax.swing.JTable();
        lblVentas = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimientos Por Área");

        btnBuscarXID.setText("Buscar");
        btnBuscarXID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarXIDActionPerformed(evt);
            }
        });

        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("Área");

        txtArea.setToolTipText("ID de Artículo");
        txtArea.setName(""); // NOI18N

        btnCerrarForm.setText("Cerrar");
        btnCerrarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFormActionPerformed(evt);
            }
        });

        dgVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID","Fecha","ID Articulo","Valor Final","Cantidad"
            }
        ));
        jScrollPane1.setViewportView(dgVentas);

        btnLimpiarGrilla.setText("Limpiar");
        btnLimpiarGrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarGrillaActionPerformed(evt);
            }
        });

        dgCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID","Fecha","ID Articulo","Valor Final","Cantidad"
            }
        ));
        jScrollPane2.setViewportView(dgCompras);

        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentas.setText("Ventas");

        lblCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompras.setText("Compras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(480, Short.MAX_VALUE)
                        .addComponent(btnLimpiarGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVentas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBuscarXID, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblArea)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCompras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarXID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Búsquedas de Artículos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarXIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarXIDActionPerformed
        try{
            String areaBuscada = this.txtArea.getText();
            ILista<IMovimiento> listaVentas = this.farmaArticulos.listarVentasXArea(areaBuscada,0);
            if (listaVentas == null){
                JOptionPane.showMessageDialog(null, "No hay ventas ingresadas", "Atención", JOptionPane.WARNING_MESSAGE);
            }else{
                this.dgVentas.setRowSelectionAllowed(true);
                this.dgVentas.setRowSelectionAllowed(true);
                DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();

                if (listaVentas != null){
                    INodoLista<IMovimiento> nodoActual = listaVentas.getPrimero();

                while (nodoActual != null){
                    IMovimiento ventaActual = nodoActual.getObjeto();
                        if (ventaActual != null){
                            String[] prodInfo = new String[12];
                            prodInfo[0] = (ventaActual.getID()).toString();
                            prodInfo[1] = ventaActual.GetFecha().toString();
                            prodInfo[2] = (ventaActual.GetIdArticulo()).toString();
                            prodInfo[3] = Double.toString(ventaActual.GetValorFinal());
                            prodInfo[4] = Integer.toString(ventaActual.GetCantidad());

                            elementTable.addRow(prodInfo);
                        }
                    nodoActual = nodoActual.getSiguiente();
                }
            }
                
            ILista<IMovimiento> listaCompras = this.farmaArticulos.listarComprasXArea(areaBuscada,0);
            if (listaCompras == null){
                JOptionPane.showMessageDialog(null, "No hay compras ingresadas", "Atención", JOptionPane.WARNING_MESSAGE);
            }else{
                this.dgCompras.setRowSelectionAllowed(true);
                this.dgCompras.setRowSelectionAllowed(true);
                DefaultTableModel elementTable1 = (DefaultTableModel) this.dgCompras.getModel();

                if (listaCompras != null){
                    INodoLista<IMovimiento> nodoActual = listaCompras.getPrimero();

                while (nodoActual != null){
                    IMovimiento ventaActual = nodoActual.getObjeto();
                        if (ventaActual != null){
                            String[] prodInfo = new String[12];
                            prodInfo[0] = (ventaActual.getID()).toString();
                            prodInfo[1] = ventaActual.GetFecha().toString();
                            prodInfo[2] = (ventaActual.GetIdArticulo()).toString();
                            prodInfo[3] = Double.toString(ventaActual.GetValorFinal());
                            prodInfo[4] = Integer.toString(ventaActual.GetCantidad());

                            elementTable1.addRow(prodInfo);
                        }
                    nodoActual = nodoActual.getSiguiente();
                }
            }
                                   
        }}}
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Ha habido un error al leer los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarXIDActionPerformed

    private void LimpiarTabla(){
        DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
        elementTable.setRowCount(0);
    }
    
    private void btnCerrarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFormActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarFormActionPerformed

    private void btnLimpiarGrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarGrillaActionPerformed
        DefaultTableModel elementTable = (DefaultTableModel) this.dgVentas.getModel();
        elementTable.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarGrillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMovimientosXArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMovimientosXArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMovimientosXArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMovimientosXArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMovimientosXArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarXID;
    private javax.swing.JButton btnCerrarForm;
    private javax.swing.JButton btnLimpiarGrilla;
    private javax.swing.JTable dgCompras;
    private javax.swing.JTable dgVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JTextField txtArea;
    // End of variables declaration//GEN-END:variables
}
