/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterFazGraFica;

import InterFazGraFica.NuevoArticulo;
import Clases.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author Lithium582
 */
public class Principal extends javax.swing.JFrame {

    private Farmacia farma;
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();        
        farma = new Farmacia("UCUPharma","Avenida SiempreViva 582","666-333-666");
        
        this.setSize(450,400);
        this.lblFondo.setSize(400,350);
        
        this.setResizable(false);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2,
                dim.height / 2 - this.getSize().height / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCargaDeArchivo = new javax.swing.JMenu();
        jmCargarArticulos = new javax.swing.JMenuItem();
        jmCargarStock = new javax.swing.JMenuItem();
        jmArticulos = new javax.swing.JMenu();
        jmNuevoArticulo = new javax.swing.JMenuItem();
        jmListarTodosArticulos = new javax.swing.JMenuItem();
        jmBuscarArticulo = new javax.swing.JMenu();
        jmBuscarArticuloXCantidad = new javax.swing.JMenuItem();
        jmBusquedaGenerica = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmEliminarArticulo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmMovimientos = new javax.swing.JMenu();
        jmNuevaVenta = new javax.swing.JMenuItem();
        jmDevolverVenta = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmListarTodasVentas = new javax.swing.JMenuItem();
        jmReportesPorFecha = new javax.swing.JMenuItem();
        jmReportesGenericos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmAcercaDe = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PurplePharma Principal");
        setBackground(new java.awt.Color(0, 0, 0));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N

        jmCargaDeArchivo.setText("Carga de Archivos");

        jmCargarArticulos.setText("Cargar Artículos");
        jmCargarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargarArticulosActionPerformed(evt);
            }
        });
        jmCargaDeArchivo.add(jmCargarArticulos);

        jmCargarStock.setText("Cargar Stock");
        jmCargarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargarStockActionPerformed(evt);
            }
        });
        jmCargaDeArchivo.add(jmCargarStock);

        jMenuBar1.add(jmCargaDeArchivo);

        jmArticulos.setText("Artículos");

        jmNuevoArticulo.setText("Nuevo");
        jmNuevoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoArticuloActionPerformed(evt);
            }
        });
        jmArticulos.add(jmNuevoArticulo);

        jmListarTodosArticulos.setText("Listar Todos");
        jmListarTodosArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarTodosArticulosActionPerformed(evt);
            }
        });
        jmArticulos.add(jmListarTodosArticulos);

        jmBuscarArticulo.setText("Buscar");

        jmBuscarArticuloXCantidad.setText("Cantidad de Artículos");
        jmBuscarArticuloXCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarArticuloXCantidadActionPerformed(evt);
            }
        });
        jmBuscarArticulo.add(jmBuscarArticuloXCantidad);

        jmBusquedaGenerica.setText("Búsqueda Genérica");
        jmBusquedaGenerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBusquedaGenericaActionPerformed(evt);
            }
        });
        jmBuscarArticulo.add(jmBusquedaGenerica);

        jmArticulos.add(jmBuscarArticulo);

        jMenu1.setText("Eliminar");

        jmEliminarArticulo.setText("Eliminar Artículo");
        jmEliminarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarArticuloActionPerformed(evt);
            }
        });
        jMenu1.add(jmEliminarArticulo);

        jMenuItem1.setText("Eliminar Área");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jmArticulos.add(jMenu1);

        jMenuBar1.add(jmArticulos);

        jmMovimientos.setText("Movimientos");

        jmNuevaVenta.setText("Nueva Venta");
        jmNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevaVentaActionPerformed(evt);
            }
        });
        jmMovimientos.add(jmNuevaVenta);

        jmDevolverVenta.setText("Devolver Venta");
        jmDevolverVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDevolverVentaActionPerformed(evt);
            }
        });
        jmMovimientos.add(jmDevolverVenta);

        jmReportes.setText("Reportes");

        jmListarTodasVentas.setText("Listar Todas");
        jmListarTodasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarTodasVentasActionPerformed(evt);
            }
        });
        jmReportes.add(jmListarTodasVentas);

        jmReportesPorFecha.setText("Reportes por Fecha");
        jmReportesPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmReportesPorFechaActionPerformed(evt);
            }
        });
        jmReportes.add(jmReportesPorFecha);

        jmReportesGenericos.setText("Reportes Genéricos");
        jmReportesGenericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmReportesGenericosActionPerformed(evt);
            }
        });
        jmReportes.add(jmReportesGenericos);

        jMenuItem2.setText("Movimientos Por Área");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmReportes.add(jMenuItem2);

        jmMovimientos.add(jmReportes);

        jMenuBar1.add(jmMovimientos);

        jmAcercaDe.setText("Acerca De");

        jMenuItem3.setText("Acerca DE...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmAcercaDe.add(jMenuItem3);

        jMenuBar1.add(jmAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCargarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargarArticulosActionPerformed

        ////Cerrar el form
        //this.dispose();
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showOpenDialog(this);
        
        /*
        ERROR_MESSAGE
        INFORMATION_MESSAGE
        WARNING_MESSAGE
        QUESTION_MESSAGE
        PLAIN_MESSAGE 
        */
        
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String direccionArchivo = selectedFile.getAbsolutePath();
            Boolean b = farma.cargarArticulos(direccionArchivo);
            
            if (b){
                JOptionPane.showMessageDialog(null, "Archivo cargado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jmCargarArticulosActionPerformed

    private void jmCargarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargarStockActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String direccionArchivo = selectedFile.getAbsolutePath();
            Boolean b = farma.cargarStock(direccionArchivo);
            
            if (b){
                JOptionPane.showMessageDialog(null, "Archivo cargado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jmCargarStockActionPerformed

    private void jmNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoArticuloActionPerformed

        
        NuevoArticulo a = new NuevoArticulo(farma);
        a.show();
    }//GEN-LAST:event_jmNuevoArticuloActionPerformed

    private void jmEliminarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarArticuloActionPerformed
        try{
            String idProductoEliminar = JOptionPane.showInputDialog(this,"Ingrese el ID del artículo a eliminar",
                    "Eliminar un artículo",JOptionPane.INFORMATION_MESSAGE);
            
            if (idProductoEliminar != null){
                Integer idProductoINT = Integer.parseInt(idProductoEliminar);
                if(farma.EliminarArticulo(idProductoINT)){
                    JOptionPane.showMessageDialog(this,"Artículo eliminado con éxito","Información",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Ha habido un error al eliminar el artículo","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmEliminarArticuloActionPerformed

    private void jmListarTodosArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarTodosArticulosActionPerformed
        frmListarArticulos fLArticulos = new frmListarArticulos(farma);
        fLArticulos.show();
    }//GEN-LAST:event_jmListarTodosArticulosActionPerformed

    private void jmBuscarArticuloXCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarArticuloXCantidadActionPerformed
        Integer iCant = farma.CantidadDeArticulos();
        JOptionPane.showMessageDialog(this,"La farmacia cuenta con " + iCant.toString() + " artículos diferentes","Información",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmBuscarArticuloXCantidadActionPerformed

    private void jmBusquedaGenericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBusquedaGenericaActionPerformed
        frmBuscarArticulos formBuscar = new frmBuscarArticulos(farma);
        formBuscar.show();
    }//GEN-LAST:event_jmBusquedaGenericaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         try{
            String strAreaEliminar = JOptionPane.showInputDialog(this,"Ingrese el área a eliminar", "Eliminar un área",JOptionPane.INFORMATION_MESSAGE);
            
            if (strAreaEliminar != null){
                if(farma.EliminarArea(strAreaEliminar)){
                    JOptionPane.showMessageDialog(this,"Área eliminada con éxito","Información",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Ha habido un error al eliminar el artículo","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmDevolverVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDevolverVentaActionPerformed
        try{
            String idVentaBuscar = JOptionPane.showInputDialog(this,"Ingrese el ID de la venta a devolver",
                    "Retornar una venta",JOptionPane.INFORMATION_MESSAGE);
            
            if (idVentaBuscar != null){
                Long idVentaLong = Long.parseLong(idVentaBuscar);
                if(farma.ReintegroVenta(idVentaLong)){
                    JOptionPane.showMessageDialog(this,"Venta reintegrada con éxito","Información",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Ha habido un error al retornar la venta","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmDevolverVentaActionPerformed

    private void jmNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevaVentaActionPerformed
        frmNuevaVenta nuevaVentaForm = new frmNuevaVenta(farma);
        nuevaVentaForm.show();
    }//GEN-LAST:event_jmNuevaVentaActionPerformed

    private void jmListarTodasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarTodasVentasActionPerformed
    frmListarVentas listarVentaForm = new frmListarVentas(farma);
        listarVentaForm.show();
    }//GEN-LAST:event_jmListarTodasVentasActionPerformed

    private void jmReportesPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmReportesPorFechaActionPerformed
        frmListarVentasXFecha formXFecha = new frmListarVentasXFecha(this.farma);
        formXFecha.show();
    }//GEN-LAST:event_jmReportesPorFechaActionPerformed

    private void jmReportesGenericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmReportesGenericosActionPerformed
        frmBuscarVentas formBuscarVentas = new frmBuscarVentas(this.farma);
        formBuscarVentas.show();
    }//GEN-LAST:event_jmReportesGenericosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmMovimientosXArea formMovimientos = new frmMovimientosXArea(farma);
        formMovimientos.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmAcercaDe formA = new frmAcercaDe(farma);
        formA.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmAcercaDe;
    private javax.swing.JMenu jmArticulos;
    private javax.swing.JMenu jmBuscarArticulo;
    private javax.swing.JMenuItem jmBuscarArticuloXCantidad;
    private javax.swing.JMenuItem jmBusquedaGenerica;
    private javax.swing.JMenu jmCargaDeArchivo;
    private javax.swing.JMenuItem jmCargarArticulos;
    private javax.swing.JMenuItem jmCargarStock;
    private javax.swing.JMenuItem jmDevolverVenta;
    private javax.swing.JMenuItem jmEliminarArticulo;
    private javax.swing.JMenuItem jmListarTodasVentas;
    private javax.swing.JMenuItem jmListarTodosArticulos;
    private javax.swing.JMenu jmMovimientos;
    private javax.swing.JMenuItem jmNuevaVenta;
    private javax.swing.JMenuItem jmNuevoArticulo;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmReportesGenericos;
    private javax.swing.JMenuItem jmReportesPorFecha;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

}
